name : Verify

on:
  push:
    branches:

  pull_request:


jobs:
  conform:
    runs-on: ubuntu-latest
    name: Conform


    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0


  build:
    name: Build with JDK 24
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: gradle
      - name: Build with Gradle
        run: ./gradlew compileJava